import Head from "next/head";
import Image from "next/image";
import { findFeaturedPosts, getAllPosts } from "../firebase/firebase-util";
import styles from "../styles/Home.module.css";
import FeaturedPosts from "../components/home/FeaturedPosts";
import Hero from "../components/home/Hero";
function HomePage(props) {
  return (
    <>
      <div className="contain">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Hero />
        <FeaturedPosts posts={props.posts} />
      </div>
    </>
  );
}

export async function getStaticProps() {
  const allPosts = await getAllPosts();
  const featuredPosts = findFeaturedPosts(allPosts);

  return {
    props: {
      posts: featuredPosts,
    },
  };
}

export default HomePage;
